/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CSE564_Project_Spring2020;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        //App classUnderTest = new App();
        assertNull(null);
    }
}
